# Day 4 — NumPy From Absolute Zero
### ADAS Engineering Journey

Concepts today:
1. What is NumPy and why it exists
2. Creating arrays
3. Array shape and dimensions
4. Indexing and slicing arrays
5. Math on arrays
6. Statistical operations
7. Boolean masking

Normal Python list — slow way:
numbers = [1, 2, 3, 4, 5]
for i in range(len(numbers)):
    numbers[i] = numbers[i] * 2
→ multiplies one number at a time
→ 5 steps for 5 numbers
→ 1 million steps for 1 million numbers

NumPy array — fast way:
numbers = np.array([1, 2, 3, 4, 5])
numbers = numbers * 2
→ multiplies ALL numbers at once
→ 1 step for any amount of numbers
→ written in C underneath — very fast

In ADAS:
Camera image = 1280 x 720 = 921,600 pixels
Processing each pixel one by one = too slow
NumPy processes all 921,600 at once = fast enough

In [1]:
# CONCEPT 1 — NUMPY IMPORT

# numpy is the library name
# np is the short nickname we give it
# so we type np.something instead of numpy.something
import numpy as np

# Check it installed correctly
print("NumPy version:", np.__version__)
print("NumPy imported successfully")

NumPy version: 1.21.5
NumPy imported successfully


In [9]:
# CONCEPT 2 — CREATING ARRAYS

import numpy as np

# Method 1 — from a Python list
distances = np.array([15.3, 28.7, 8.2, 12.1, 45.6])
print("From list:", distances)

# Method 2 — all zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Method 3 — all ones
ones = np.ones(5)
print("Ones:", ones)

# Method 4 — range of numbers
# arange(start, stop, step)
numbers = np.arange(0, 10, 2)
print("Arange:", numbers)

# Method 5 — evenly spaced between two numbers
# linspace(start, stop, how_many_points)
spaced = np.linspace(0, 1, 5)
print("Linspace:", spaced)

# Method 6 — random numbers
np.random.seed(42)     # seed makes random reproducible
random = np.random.randn(5)
print("Random:", random)

From list: [15.3 28.7  8.2 12.1 45.6]
Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]


In [10]:
# Python list
py_list = [1, 2, 3, 4, 5]

# NumPy array
np_array = np.array([1, 2, 3, 4, 5])

print("Python list  :", py_list)
print("NumPy array  :", np_array)
print("Type of list :", type(py_list))
print("Type of array:", type(np_array))
print("dtype of array:", np_array.dtype)

Python list  : [1, 2, 3, 4, 5]
NumPy array  : [1 2 3 4 5]
Type of list : <class 'list'>
Type of array: <class 'numpy.ndarray'>
dtype of array: int64


In [20]:
# TASK 2
# Create these arrays and print each one:
# 1. An array from this list: [10, 20, 30, 40, 50]
# 2. An array of 6 zeros
# 3. An array of 4 ones
# 4. An array of even numbers from 2 to 10 using arange
# 5. An array of 5 evenly spaced numbers between 0 and 100

# Write below:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print(array)

zeros = np.zeros(6)
print(zeros)

onces = np.ones(4)
print(ones)

arrays = np.arange(0, 12, 2)
print(arrays)

arrayss =np.linspace(0, 100, 5)
print(arrayss)

[10 20 30 40 50]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 0  2  4  6  8 10]
[  0.  25.  50.  75. 100.]


In [26]:
# CONCEPT 3 — SHAPE AND DIMENSIONS

import numpy as np

# 1D array — one row of numbers
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array:", arr_1d)
print("Shape:", arr_1d.shape)      # (5,) means 5 elements
print("Dimensions:", arr_1d.ndim)  # 1 dimension
print()

# 2D array — rows and columns like a table
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("2D array:\n", arr_2d)
print("Shape:", arr_2d.shape)      # (3, 3) means 3 rows 3 columns
print("Dimensions:", arr_2d.ndim)  # 2 dimensions
print()

# 3D array — like a colour image
# shape (height, width, channels)
arr_3d = np.zeros((4, 4, 3))
print("3D array shape:", arr_3d.shape)   # (4, 4, 3)
print("Dimensions:", arr_3d.ndim)        # 3 dimensions

1D array: [1 2 3 4 5]
Shape: (5,)
Dimensions: 1

2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2

3D array shape: (4, 4, 3)
Dimensions: 3


Camera image shape:  (720, 1280, 3)
                      height  width  RGB channels

LiDAR point cloud:   (120000, 4)
                       points  x,y,z,intensity

Batch of images:     (32, 720, 1280, 3)
                      batch   height  width  channels

When you load an image with OpenCV later in the course
it will be a NumPy array with shape (height, width, 3)
Understanding shape is essential

In [37]:
# TASK 3
# Create these arrays and print their shape and dimensions:
# 1. 1D array: [5, 10, 15, 20]
# 2. 2D array: two rows, three columns with numbers 1 to 6
# 3. Array of zeros with shape (720, 1280, 3) — fake camera image
#    Just print the shape, not the whole array

# Write below:

arr_1d = np.array([5, 10, 15, 20])
print(arr_1d)

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr_2d)

camera_image = np.zeros((720, 1280, 3))

print(f"Shape:{arr_1d.shape}, Dimension:{arr_1d.ndim}")
print(f"Shape:{arr_2d.shape}, Dimension:{arr_2d.ndim}")
print(f"Fake image shape:{camera_image.shape}")

[ 5 10 15 20]
[[1 2 3]
 [4 5 6]]
Shape:(4,), Dimension:1
Shape:(2, 3), Dimension:2
Fake image shape:(720, 1280, 3)


In [38]:
# CONCEPT 4 — INDEXING AND SLICING

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Single element — same as Python list
print(arr[0])     # 10 — first
print(arr[-1])    # 70 — last
print(arr[2])     # 30 — third

# Slicing — same as Python list
print(arr[0:3])   # [10 20 30]
print(arr[2:5])   # [30 40 50]
print(arr[:3])    # [10 20 30]
print(arr[4:])    # [50 60 70]
print(arr[::2])   # [10 30 50 70] every 2nd
print(arr[::-1])  # [70 60 50 40 30 20 10] reversed

10
70
30
[10 20 30]
[30 40 50]
[10 20 30]
[50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [2]:
# 2D array indexing
# arr[row, column]
import numpy as np
arr2d = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9, 10, 11, 12]
])

print("Full array:\n", arr2d)
print()

# Single element
print("Row 0, Col 0:", arr2d[0, 0])    # 1
print("Row 1, Col 2:", arr2d[1, 2])    # 7
print("Row 2, Col 3:", arr2d[2, 3])    # 12

# Entire row
print("Row 0:", arr2d[0])              # [1 2 3 4]
print("Row 1:", arr2d[1])              # [5 6 7 8]

# Entire column
print("Col 0:", arr2d[:, 0])           # [1 5 9]
print("Col 2:", arr2d[:, 2])           # [3 7 11]

# Subarray
print("Rows 0-1, Cols 1-2:\n", arr2d[0:2, 1:3])

Full array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Row 0, Col 0: 1
Row 1, Col 2: 7
Row 2, Col 3: 12
Row 0: [1 2 3 4]
Row 1: [5 6 7 8]
Col 0: [1 5 9]
Col 2: [ 3  7 11]
Rows 0-1, Cols 1-2:
 [[2 3]
 [6 7]]


In [16]:
# TASK 4
# This represents LiDAR data
# Each row is one point: [x, y, z, intensity]
lidar_data = np.array([
    [1.5,  2.3,  0.1, 45.0],
    [3.2,  1.1, -0.2, 67.0],
    [5.7,  4.8,  0.3, 23.0],
    [2.1,  6.2, -0.1, 89.0],
    [8.3,  3.5,  0.2, 34.0],
])

# 1. Print the first point (row 0)
# 2. Print the x coordinate of the third point
# 3. Print ALL x coordinates (column 0)
# 4. Print ALL intensity values (column 3)
# 5. Print first 3 points only

# Write below:
print("Row 0:",lidar_data[0])
print("X of point 3:",lidar_data[2, 0])
print("All X of column 0:",lidar_data[:, 0] )
print("All intensity:",lidar_data[:, 3])
print("First 3 points:\n",lidar_data[0:3])

Row 0: [ 1.5  2.3  0.1 45. ]
X of point 3: 5.7
All X of column 0: [1.5 3.2 5.7 2.1 8.3]
All intensity: [45. 67. 23. 89. 34.]
First 3 points:
 [[ 1.5  2.3  0.1 45. ]
 [ 3.2  1.1 -0.2 67. ]
 [ 5.7  4.8  0.3 23. ]]


In [17]:
# CONCEPT 5 — MATH ON ARRAYS

import numpy as np

distances = np.array([10.0, 20.0, 30.0, 40.0, 50.0])

# Add a number to every element
print("Original:", distances)
print("Add 5   :", distances + 5)
print("Subtract:", distances - 5)
print("Multiply:", distances * 2)
print("Divide  :", distances / 10)
print("Power   :", distances ** 2)
print()

# Math between two arrays — element by element
array_a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
array_b = np.array([10.0, 20.0, 30.0, 40.0, 50.0])

print("A + B:", array_a + array_b)
print("A * B:", array_a * array_b)
print("A / B:", array_a / array_b)

Original: [10. 20. 30. 40. 50.]
Add 5   : [15. 25. 35. 45. 55.]
Subtract: [ 5. 15. 25. 35. 45.]
Multiply: [ 20.  40.  60.  80. 100.]
Divide  : [1. 2. 3. 4. 5.]
Power   : [ 100.  400.  900. 1600. 2500.]

A + B: [11. 22. 33. 44. 55.]
A * B: [ 10.  40.  90. 160. 250.]
A / B: [0.1 0.1 0.1 0.1 0.1]


In [46]:
# TASK 5
# You have radar readings in metres
readings_m = np.array([15.3, 28.7, 8.2, 12.1, 45.6])

# 1. Print the readings as they are
# 2. Convert to centimetres (multiply by 100) and print
# 3. Convert to feet (multiply by 3.281) and print with 2 decimal places
# 4. You have closing speeds in m/s:
speeds = np.array([5.0, 8.0, 3.0, 10.0, 2.0])
# Calculate TTC for each reading (distance / speed) and print
# Round to 2 decimal places using .round(2)

# Write below

print("Meters:",readings_m)
print("Centimeters:",readings_m * 100)
print(f"Feet:{(readings_m * 3.281).round(2)}")

print("TTC:",(readings_m/speeds).round(2))

Meters: [15.3 28.7  8.2 12.1 45.6]
Centimeters: [1530. 2870.  820. 1210. 4560.]
Feet:[ 50.2   94.16  26.9   39.7  149.61]
TTC: [ 3.06  3.59  2.73  1.21 22.8 ]


In [49]:
# CONCEPT 6 — STATISTICAL OPERATIONS

import numpy as np

# Simulate 10 radar distance readings
# True distance is 25m but sensor has noise
np.random.seed(0)
true_distance = 25.0
noise         = np.random.randn(10) * 0.5
readings      = true_distance + noise

print("Readings:", readings.round(2))
print()
print("Minimum  :", readings.min().round(2))
print("Maximum  :", readings.max().round(2))
print("Mean     :", readings.mean().round(2))
print("Std Dev  :", readings.std().round(2))
print("Sum      :", readings.sum().round(2))
print()

# Index of min and max
print("Index of min:", readings.argmin())
print("Index of max:", readings.argmax())
print("Value at min:", readings[readings.argmin()].round(3))
print("Value at max:", readings[readings.argmax()].round(3))


Readings: [25.88 25.2  25.49 26.12 25.93 24.51 25.48 24.92 24.95 25.21]

Minimum  : 24.51
Maximum  : 26.12
Mean     : 25.37
Std Dev  : 0.48
Sum      : 253.69

Index of min: 5
Index of max: 3
Value at min: 24.511
Value at max: 26.12


In [69]:
# TASK 6
# You recorded confidence scores from your YOLO model
# across 8 detections
confidence_scores = np.array([0.92, 0.87, 0.45, 0.78,
                               0.91, 0.63, 0.88, 0.55])

# 1. Print the highest confidence score
# 2. Print the lowest confidence score
# 3. Print the average confidence score (2 decimal places)
# 4. Print the standard deviation (3 decimal places)
# 5. Print which index has the highest score
# 6. Print how many scores are above 0.80
#    Hint: use a comparison then sum()
#    np.sum(confidence_scores > 0.80)

# Write below:
print(f"The Highest: {(confidence_scores.max()).round(2)}")
print(f"The Lowest: {(confidence_scores.min()).round(2)}")
print(f"The Average: {(confidence_scores.mean()).round(2)}")
print(f"The Standard Devi: {(confidence_scores.std()).round(2)}")
print(f"The Index of Higest: {confidence_scores.argmax()}")
print(f"The Index of Lowest: {confidence_scores.argmin()}")
n = np.sum(confidence_scores > 0.80)
print(f"Scores above 0.80: {n}")

The Highest: 0.92
The Lowest: 0.45
The Average: 0.75
The Standard Devi: 0.17
The Index of Higest: 0
The Index of Lowest: 2
Scores above 0.80: 4


In [72]:
# CONCEPT 7 — BOOLEAN MASKING

import numpy as np

distances = np.array([15.3, 28.7, 8.2, 12.1, 45.6, 33.2, 7.8])

# Step 1 — Create a boolean mask
# Each element becomes True or False based on the condition
mask = distances < 15.0
print("Distances:", distances)
print("Mask     :", mask)
print()

# Step 2 — Use the mask to filter the array
# Only elements where mask is True are kept
dangerous = distances[mask]
print("Dangerous distances (<15m):", dangerous)
print()

# Do it in one line
very_close = distances[distances < 10.0]
print("Very close (<10m):", very_close)

# Multiple conditions
# & means AND   | means OR
moderate = distances[(distances >= 10.0) & (distances < 25.0)]
print("Moderate risk (10-25m):", moderate)

# Count how many satisfy condition
count = np.sum(distances < 15.0)
print("Count below 15m:", count)

Distances: [15.3 28.7  8.2 12.1 45.6 33.2  7.8]
Mask     : [False False  True  True False False  True]

Dangerous distances (<15m): [ 8.2 12.1  7.8]

Very close (<10m): [8.2 7.8]
Moderate risk (10-25m): [15.3 12.1]
Count below 15m: 3


In [73]:
# TASK 7 — FINAL CHALLENGE
# Sensor data: distance readings from 10 frames
np.random.seed(5)
sensor_readings = np.random.uniform(5, 60, 10).round(1)

print("All readings:", sensor_readings)

# Using boolean masking — no loops allowed:
# 1. Print readings below 15m (danger zone)
# 2. Print readings between 15m and 30m (warning zone)
# 3. Print readings above 30m (safe zone)
# 4. Print count of readings in each zone
# 5. Print percentage of readings in danger zone
#    (danger count / total count * 100)
#    Round to 1 decimal place

# Write below:
import numpy as np

# Sensor data
np.random.seed(5)
sensor_readings = np.random.uniform(5, 60, 10).round(1)

print("All readings:", sensor_readings)

# Boolean masking
danger = sensor_readings < 15
warning = (sensor_readings >= 15) & (sensor_readings <= 30)
safe = sensor_readings > 30

print("Danger zone:", sensor_readings[danger])
print("Warning zone:", sensor_readings[warning])
print("Safe zone:", sensor_readings[safe])

danger_count = np.sum(danger)
warning_count = np.sum(warning)
safe_count = np.sum(safe)

print("Danger count:", danger_count)
print("Warning count:", warning_count)
print("Safe count:", safe_count)

danger_percent = round((danger_count / len(sensor_readings)) * 100, 1)

print("Danger percentage:", danger_percent, "%")

All readings: [17.2 52.9 16.4 55.5 31.9 38.6 47.1 33.5 21.3 15.3]
All readings: [17.2 52.9 16.4 55.5 31.9 38.6 47.1 33.5 21.3 15.3]
Danger zone: []
Warning zone: [17.2 16.4 21.3 15.3]
Safe zone: [52.9 55.5 31.9 38.6 47.1 33.5]
Danger count: 0
Warning count: 4
Safe count: 6
Danger percentage: 0.0 %
